### ISSUE TITLE
Client is crashing while exploring end, server not.

### ISSUE THREAD

**Issue by TheButterbrotMan** [DakotaPride/More-Weaponry-1.18#6]
More Weaponry v1.18+1.18.2
fabric: Fabric API 0.48.0+1.18.2

https://bytebin.lucko.me/CNCBKIJVRq

Just ask if you need more information! :)

**Comment by DakotaPride** [comment]
I believe that I have fixed it, I'll post another Alpha sometime within the next couple of days.

What I think the issue might've been:
I was registering my Block Entities (while it was only the Cirtict Forge in this scenario) in the Main Initializer instead of registering it on the Client Initializer, which could have caused it to crash on the Client-side. With this being said, it was difficult to replicate, as it hadn't happened to me before while testing the block entities nor did it happen while editing the code from Main to Client.

edit: I'm gonna actually leave this issue open until I post that alpha in case this didn't fix the issue.

**Comment by DakotaPride** [comment]
I've uploaded the new updated file to curseforge, hopefully, they approve it soon
(The first time they had rejected it for an unknown reason, but it's currently under review)
