### ISSUE TITLE
Mod behaves weirdly on Quilt

### ISSUE THREAD

**Issue by Sunconure11** [DakotaPride/More-Weaponry-1.18#7]
https://pastebin.com/izD06Jgg

**Comment by DakotaPride** [comment]
> That is due to this mod being designed for Fabric and not Quilt. Even though Quilt and Fabric are similar to my knowledge, they are still different and cannot be expected to behave the exact same. I do not currently have plans to port this mod over to Quilt, though that could change in the future. If you have any more questions, please feel free to let me know!

**Comment by DakotaPride** [comment]
@Sunconure11 Sidenote, after going ahead and installing the Quilt Modloader, More Weaponry seems to be acting fine, as well as Incantation. (If you would like to continue this conversation further, please leave it to just one of the issues pages, so that it's easier to manage) If you could please specify exactly what's not acting properly, that would help a lot.

Edit: Another sidenote, I'm planning on releasing a patch to More Weaponry very soon that could potentially fix your issue, as looking in the report itself, it seems that it's due to More Weaponry requiring a specific version of fabric API installed (0.55.3+1.19). If you do not already have this version installed, please try it, to see if that solves your issue. Again, just let me know if you have any other questions or any other concerns regarding this issue!

**Comment by Sunconure11** [comment]
Quilt bundles it's own version of the Fabric API, FYI

**Comment by DakotaPride** [comment]
> Quilt bundles it's own version of the Fabric API, FYI

I may need to do some more research into Quilt, as I'm not very experienced with it. But depending on what's acting strange relating to More Weaponry/Incantation, it could be a very minor difference between the two apis.

**Comment by DakotaPride** [comment]
@Sunconure11 
Issue Should Now Be Resolved In [More Weaponry v1.19.4](https://www.curseforge.com/minecraft/mc-mods/more-weaponry/files/3879937)
